### ISSUE TITLE
Google Sheets Connector not Working

### ISSUE THREAD

**Issue by dyaffe** [estuary/airbyte#170]
Our Google Sheets connector is currently facing an issue:

```
[ghcr.io/estuary/source-google-sheets:v1](http://ghcr.io/estuary/source-google-sheets:v1)
1
ERRO
[0003] Missing required parameter "spreadsheetId"
2
Traceback (most recent call last):
3
  File "/airbyte/integration_code/main.py", line 13, in <module>
4
    launch(source, sys.argv[1:])
5
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 156, in launch
6
    for message in source_entrypoint.run(parsed_args):
7
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 93, in run
8
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.discover(source_spec, config))
9
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 124, in discover
10
    catalog = self.source.discover(self.logger, config)
11
  File "/airbyte/integration_code/google_sheets_source/google_sheets_source.py", line 107, in discover
12
    spreadsheet_metadata = Spreadsheet.parse_obj(client.get(spreadsheetId=spreadsheet_id, includeGridData=False))
13
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
14
    ret = target(*args, **kwargs)
15
  File "/airbyte/integration_code/google_sheets_source/client.py", line 27, in get
16
    return self.client.get(**kwargs).execute()
17
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/discovery.py", line 1063, in method
18
    raise TypeError('Missing required parameter "%s"' % name)
19
TypeError: Missing required parameter "spreadsheetId"
20
ERRO
[0003] Error: Stream is empty, expected to find a message but could not find any
21
ERRO
[0003] connector failed                              
module
="connector_init::rpc" 
status
="exit status: 1"
22
WARN
[0003] connector exited with unconsumed input stream remainder  
module
="connector_init::rpc"
23
FATA
[0004] fatal error                                   
err
="invocation failed: connector failed (exit status: 1) with stderr:
{"timestamp":"2023-05-07T17:56:17.028471365Z","level":"ERROR","message":"Missing required parameter \\"spreadsheetId\\"\
Traceback (most recent call last):\
  File \\"/airbyte/integration_code/main.py\\", line 13, in <module>\
    launch(source, sys.argv[1:])\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 156, in launch\
    for message in source_entrypoint.run(parsed_args):\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 93, in run\
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.discover(source_spec, config))\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 124, in discover\
    catalog = self.source.discover(self.logger, config)\
  File \\"/airbyte/integration_code/google_sheets_source/google_sheets_source.py\\", line 107, in discover\
    spreadsheet_metadata = Spreadsheet.parse_obj(client.get(spreadsheetId=spreadsheet_id, includeGridData=False))\
  File \\"/usr/local/lib/python3.9/site-packages/backoff/_sync.py\\", line 105, in retry\
    ret = target(*args, **kwargs)\
  File \\"/airbyte/integration_code/google_sheets_source/client.py\\", line 27, in get\
    return self.client.get(**kwargs).execute()\
  File \\"/usr/local/lib/python3.9/site-packages/googleapiclient/discovery.py\\", line 1063, in method\
    raise TypeError('Missing required parameter \\"%s\\"' % name)\
TypeError: Missing required parameter \\"spreadsheetId\\""}
Error: Stream is empty, expected to find a message but could not find any
"
```

cc @mdibaiee

**Comment by mdibaiee** [comment]
@dyaffe I can't reproduce this, I just created a new Google Sheets capture and it worked just fine 🤔

**Comment by dyaffe** [comment]
Will try to get a reproduction and get back to you.
